# 基础配置
baidu_url: 'https://www.baidu.com/'
# 填写电话号码
tel_number: '13800000000'
# 填写真实姓名
tel_name: '张伟'
# 填写代理
proxy: 'http://127.0.0.1:7890'

# 填写本机 chrome 的路径, 一般安装位置在 C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
browser_path: 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'

# 留言模板 — 随机组合生成
titles:
  - "医生"
  - "护士"
  - "主任"
  - "医师"
  - "院长"
  - "专家"
  - "同志"
  - "大夫"

relatives:
  - "我的外公"
  - "我的外婆"
  - "我的父亲"
  - "我的母亲"
  - "我的哥哥"
  - "我的姐姐"
  - "我的弟弟"
  - "我的妹妹"
  - "我的表兄弟"
  - "我的表姐妹"
  - "我的堂兄弟"
  - "我的堂姐妹"
  - "我老婆"
  - "我丈夫"
  - "我妻子"
  - "我的妻子"
  - "我自己"
  - "我本人"
  - "我大姨"
  - "我小姨"
  - "我的大姑子"
  - "我的小姑子"
  - "我的大舅子"
  - "我的小舅子"

situations:
  - "有一些毛病"
  - "需要帮助"
  - "需要您的帮助"
  - "需要医疗建议"
  - "需要治疗"
  - "需要紧急处理"
  - "有紧急情况"
  - "需要进行检查"
  - "需要手术治疗"
  - "生病了"
  - "情况不太好"
  - "需要紧急救治"
  - "需要安排手术"
  - "需要进一步诊断"

contact_methods:
  - "我急需帮助，请尽快联系我 {number}"
  - "有事找你，麻烦联系我 {number}"
  - "情况紧急，请求帮助，请立即拨打 {number}"
  - "需要紧急救助，请马上联系我 {number}"
  - "我的病情急需处理，请尽快联系 {number}"
  - "需要安排紧急手术，请与我联系 {number}"
  - "有重要情况需要讨论，请拨打 {number} 联系我"
  - "我有紧急问题，希望能与你通话 {number}"
  - "请尽快与我联系，电话号码是 {number}"
  - "通过 {number} 联系我"
  - "请联系 {number}"
  - "可以通过 {number} 找到我"
  - "请拨打 {number}"
  - "有急事，请立即拨打 {number}"
  - "需要紧急帮助，请马上拨打 {number}"
  - "需要紧急医疗服务，请联系 {number}"
  - "有重要事项需要沟通，请拨打 {number}"
  - "需要迅速安排治疗，请联系 {number}"
  - "请随时与我联系，电话号码是 {number}"
  - "请拨打 {number}"

greetings:
  - "您好"
  - "你好"
  - "hello"
  - "hi"
  - "HI"
  - "Hello"
  - "早上好"
  - "下午好"
  - "晚上好"
  - "Hi there"
  - "Hey"
